version: "3.8"
services:
  database:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
    ports: 
      - 5432:5432
  backend:
    build: ./backend
    command: gunicorn -t 150 app:app --bind 0.0.0.0:5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      PYTHONUNBUFFERED: definetely
    ports:
      - "5000:5000"
    depends_on:
      - database
  frontend:
    build: ./frontend
    command: bash -c "yarn run start"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
