version: "3.8"
services:
  database:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
    ports: 
      - 5432:5432
  backend:
    build: ./backend
    command: flask run -p 5000 --host=0.0.0.0 
    volumes:
      - ./frontend:/app
    ports:
      - "5000:5000"
    depends_on:
      - database
  frontend:
    build: ./frontend
    command: bash -c "yarn run start"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
