FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN ls -a
ENV host=host.docker.internal

CMD ["gunicorn" "-t" "150" "app:app" "--bind" "0.0.0.0:5000"]