FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN ls -a
ENV host=host.docker.internal

CMD ["python" "flask" "run" "-p" "5000" "--host=0.0.0.0"]