name: Lint

on: [push]

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          black_args: "./backend --check"

  lint_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install packages
      run: |
        cd frontend
        yarn install
    - name: Run linter
      run: |
        cd frontend
        yarn lint