name: Unit

on: [push, pull_request]

jobs:
  frontend_unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install packages
        run: |
          cd frontend
          yarn install
      - name: Run unit tests
        run: |
          cd frontend
          yarn test

  backend_unit:
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-interval 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Installing dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Configuring database
        env:
          host: localhost
        run: |
          cd backend
          alembic upgrade head -c alembic-ci.ini
          python seeder.py -p
      - name: Running tests
        env:
          host: localhost
        run: |
          cd backend
          coverage run -m pytest -vv